// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.viewunite.v1;

enum BizType {
  BizTypeNone = 0;
  BizTypeFollowVideo = 1;
  BizTypeReserveActivity = 2;
  BizTypeJumpLink = 3;
  BizTypeFavSeason = 4;
  BizTypeReserveGame = 5;
  BizTypeGiftGame = 6;
  UNRECOGNIZED = -1;
}

enum ButtonAction {
  BUTTON_ACTION_DEFAULT = 0;
  BUTTON_ACTION_CANCEL = 1;
  UNRECOGNIZED = -1;
}

enum CacheCode {
  PLAY = 0;
  UPOWERSTATE_INACTIVE = 100;
  REPEAT_LAST_OPERATION = 101;
  UNRECOGNIZED = -1;
}

enum ECode {
  CODE_DEFAULT = 0;
  CODE_404 = 1;
  CODE_ARC_PRIVACY = 2;
  CODE_TEENAGER = 78301;
  UNRECOGNIZED = -1;
}

enum JumpShowType {
  JST_DEFAULT = 0;
  JST_FULLSCREEN = 1;
  JST_HALFSCREEN = 2;
  UNRECOGNIZED = -1;
}

enum MaterialBizType {
  NONE = 0;
  ACTIVITY = 1;
  BGM = 2;
  EFFECT = 3;
  SHOOT_SAME = 4;
  SHOOT_TOGETHER = 5;
  ACTIVITY_ICON = 6;
  NEW_BGM = 7;
  GENERAL_TYPE = 8;
  UNRECOGNIZED = -1;
}

enum MaterialSource {
  DEFAULT = 0;
  BIJIAN = 1;
  UNRECOGNIZED = -1;
}

enum PageCategory {
  COMMON_PAGE = 0;
  ACTIVITY_PAGE = 1;
  UNRECOGNIZED = -1;
}

enum PageType {
  H5 = 0;
  NA = 1;
  UNRECOGNIZED = -1;
}

enum PauseType {
  PAUSE_TYPE_DEFAULT = 0;
  PAUSE_TYPE_ADS = 1;
  UNRECOGNIZED = -1;
}

enum PlayToastEnum {
  PLAYTOAST_UNKNOWN = 0;
  PLAYTOAST_CHARGINGPLUS = 1;
  UNRECOGNIZED = -1;
}

enum SourceContentType {
  SC_DEFAULT = 0;
  SC_AV = 1;
  SC_LIVE = 2;
  UNRECOGNIZED = -1;
}

enum TabType {
  TAB_NONE = 0;
  TAB_INTRODUCTION = 1;
  TAB_REPLY = 2;
  TAB_OGV_ACTIVITY = 3;
  TAB_CATALOG = 4;
  UNRECOGNIZED = -1;
}

enum UnionType {
  UGC = 0;
  OGV = 1;
  PUGV = 2;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/app/viewunite/v1/ActivityResource.java
message ActivityResource {
  string darkTextColor = 1;
  string dividerColor = 2;
  string bgColor = 3;
  string selectedBgColor = 4;
  string textColor = 5;
  string lightTextColor = 6;
}

// Source: com/bapis/bilibili/app/viewunite/v1/CachePlayAv.java
message CachePlayAv {
  int64 aid = 1;
}

// Source: com/bapis/bilibili/app/viewunite/v1/CachePlayAvRly.java
message CachePlayAvRly {
  CacheCode code = 1;
}

// Source: com/bapis/bilibili/app/viewunite/v1/ContractText.java
message ContractText {
  string title = 1;
  string subtitle = 2;
  string inlineTitle = 3;
}

// Source: com/bapis/bilibili/app/viewunite/v1/Control.java
message Control {
  bool limit = 1;
}

// Source: com/bapis/bilibili/app/viewunite/v1/FragmentArc.java
message FragmentArc {
  int64 aid = 1;
  int64 cid = 2;
}

// Source: com/bapis/bilibili/app/viewunite/v1/PauseSourceContentList.java
message PauseSourceContentList {
  Any sourceContent = 1;
  repeated PauseAdsAV av = 2;
}

// Source: com/bapis/bilibili/app/viewunite/v1/PlayToast.java
message PlayToast {
  PlayToastEnum business = 1;
  string iconUrl = 2;
  string text = 3;
}

// Source: com/bapis/bilibili/app/viewunite/v1/ShowTime.java
message ShowTime {
  int32 startTime = 1;
  int32 endTime = 2;
  double posX = 3;
  double posY = 4;
}

// Source: com/bapis/bilibili/app/viewunite/v1/StoryActualCardWrapper.java
message StoryActualCardWrapper {
  oneof oneof_0 {
    StoryVideoCard videoCard = 1;
  }
  enum ActualCardCase {
    VIDEO_CARD = 1;
    ACTUALCARD_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/app/viewunite/v1/UpperInfos.java
message UpperInfos {
  int64 fansCount = 1;
  int64 arcCountLastHalfYear = 2;
  int64 firstUpDates = 3;
  int64 totalPlayCount = 4;
}

// Source: com/bapis/bilibili/app/viewunite/v1/VideoShot.java
message VideoShot {
  string pvData = 1;
  int32 imgXLen = 2;
  int32 imgYLen = 3;
  int32 imgXSize = 4;
  int32 imgYSize = 5;
  repeated string image = 6;
}

// Source: com/bapis/bilibili/app/viewunite/v1/ViewEndPageCard.java
message ViewEndPageCard {
  RelateCard relate = 1;
  int64 cardIndex = 2;
}

