// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.relation.interfaces;

enum Act {
  ACT_NA = 0;
  ACT_ADD_FOLLOWING = 1;
  ACT_DEL_FOLLOWING = 2;
  ACT_ADD_WHISPER = 3;
  ACT_DEL_WHISPER = 4;
  ACT_ADD_BLACK = 5;
  ACT_DEL_BLACK = 6;
  ACT_DEL_FOLLOWER = 7;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/relation/interfaces/AtGroup.java
message AtGroup {
  Type groupType = 1;
  string groupName = 2;
  repeated AtItem items = 3;
  enum Type {
    AT_GROUP_TYPE_DEFAULT = 0;
    AT_GROUP_TYPE_RECENT = 1;
    AT_GROUP_TYPE_FOLLOW = 2;
    AT_GROUP_TYPE_FANS = 3;
    AT_GROUP_TYPE_OTHERS = 4;
    UNRECOGNIZED = -1;
  }

}

