// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.mall.tab3.viewunite.v1;

enum BizType {
  BizTypeNone = 0;
  BizTypeFollowVideo = 1;
  BizTypeReserveActivity = 2;
  BizTypeJumpLink = 3;
  BizTypeFavSeason = 4;
  BizTypeReserveGame = 5;
  UNRECOGNIZED = -1;
}

enum ECode {
  CODE_DEFAULT = 0;
  CODE_404 = 1;
  CODE_TEENAGER = 78301;
  UNRECOGNIZED = -1;
}

enum JumpShowType {
  JST_DEFAULT = 0;
  JST_FULLSCREEN = 1;
  JST_HALFSCREEN = 2;
  UNRECOGNIZED = -1;
}

enum MaterialBizType {
  NONE = 0;
  ACTIVITY = 1;
  BGM = 2;
  EFFECT = 3;
  SHOOT_SAME = 4;
  SHOOT_TOGETHER = 5;
  ACTIVITY_ICON = 6;
  NEW_BGM = 7;
  UNRECOGNIZED = -1;
}

enum MaterialSource {
  DEFAULT = 0;
  BIJIAN = 1;
  UNRECOGNIZED = -1;
}

enum PageCategory {
  COMMON_PAGE = 0;
  ACTIVITY_PAGE = 1;
  UNRECOGNIZED = -1;
}

enum PageType {
  H5 = 0;
  NA = 1;
  UNRECOGNIZED = -1;
}

enum PlayToastEnum {
  PLAYTOAST_UNKNOWN = 0;
  PLAYTOAST_CHARGINGPLUS = 1;
  UNRECOGNIZED = -1;
}

enum TabType {
  TAB_NONE = 0;
  TAB_INTRODUCTION = 1;
  TAB_REPLY = 2;
  TAB_OGV_ACTIVITY = 3;
  UNRECOGNIZED = -1;
}

enum UnionType {
  UGC = 0;
  OGV = 1;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ChronosParam.java
message ChronosParam {
  string engineVersion = 1;
  string messageProtocol = 2;
  string serviceKey = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ContractText.java
message ContractText {
  string title = 1;
  string subtitle = 2;
  string inlineTitle = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/Control.java
message Control {
  bool limit = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/PlayToast.java
message PlayToast {
  PlayToastEnum business = 1;
  string iconUrl = 2;
  string text = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ShowTime.java
message ShowTime {
  int32 startTime = 1;
  int32 endTime = 2;
  double posX = 3;
  double posY = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/UpperInfos.java
message UpperInfos {
  int64 fansCount = 1;
  int64 arcCountLastHalfYear = 2;
  int64 firstUpDates = 3;
  int64 totalPlayCount = 4;
}

