// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.show.mixture.v1;

enum GuideStyleVersion {
  GUIDE_STYLE_DEFAULT = 0;
  GUIDE_STYLE_FUNC_NEW = 1;
  UNRECOGNIZED = -1;
}

enum GuideType {
  GUIDE_TYPE_DEFAULT = 0;
  GUIDE_TYPE_FUNC = 1;
  UNRECOGNIZED = -1;
}

enum RegionCardType {
  REGION_CARD_TYPE_DEFAULT = 0;
  REGION_CARD_TYPE_AV = 1;
  UNRECOGNIZED = -1;
}

enum RegionLimitCode {
  REGION_LIMIT_CODE_DEFAULT = 0;
  REGION_LIMIT_CODE_NO_LOGIN = 1;
  REGION_LIMIT_CODE_MAX = 2;
  REGION_LIMIT_CODE_ERROR = 3;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/app/show/mixture/v1/RegionContent.java
message RegionContent {
  string title = 1;
  repeated RegionIcon icons = 2;
}

// Source: com/bapis/bilibili/app/show/mixture/v1/RegionLimit.java
message RegionLimit {
  RegionLimitCode code = 1;
  string message_ = 2;
}

// Source: com/bapis/bilibili/app/show/mixture/v1/WidgetItem.java
message WidgetItem {
  string cover = 1;
  string view = 2;
  RcmdReason rcmdReason = 3;
  string title = 4;
  string name = 5;
  string uri = 6;
  string goto = 7;
  int64 id = 8;
  int32 viewIcon = 9;
}

